# Generated by Django 4.2.19 on 2025-03-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='daily_chat_quota',
            new_name='daily_message_quota',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_chat_reset',
            new_name='last_message_reset',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='chats_used_today',
            new_name='messages_used_today',
        ),
    ]
