# Generated by Django 4.2.17 on 2024-12-14 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this conversation was created')),
                ('title', models.CharField(blank=True, help_text='Title of the conversation', max_length=255)),
                ('user', models.ForeignKey(help_text='The user in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this message was sent')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('system', 'System Message'), ('notification', 'Notification')], default='user', help_text='The type of this message', max_length=20)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('user', models.ForeignKey(help_text='The user in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
