# Generated by Django 4.2.17 on 2024-12-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_addChatModels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='title',
        ),
    ]
