# Generated by Django 5.2.5 on 2025-11-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
                sql="""
                ALTER TABLE chats_message
                DROP CONSTRAINT chats_message_chat_id_f3080004_fk_chats_chat_id,
                ADD CONSTRAINT chats_message_chat_id_f3080004_fk_chats_chat_id
                FOREIGN KEY (chat_id)
                REFERENCES chats_chat (id)
                ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED;
                """,
                reverse_sql="""
                ALTER TABLE chats_message
                DROP CONSTRAINT chats_message_chat_id_f3080004_fk_chats_chat_id,
                ADD CONSTRAINT chats_message_chat_id_f3080004_fk_chats_chat_id
                FOREIGN KEY (chat_id)
                REFERENCES chats_chat (id)
                ON DELETE NO ACTION
                DEFERRABLE INITIALLY DEFERRED;
                """,
        )
    ]
