# Generated by Django 5.2.5 on 2026-01-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_add_db_cascade_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data such as sources for assistant messages'),
        ),
    ]
